### ISSUE TITLE
Slic3r Required?

### ISSUE THREAD

**Issue by jneilliii** [eyal0/OctoPrint-GcodeAnalyzer#1]
I think this may be a left over from your previous work on integrating with Slic3r plugin, but is the reference necessary for this plugin to work?  Upon install I got the below error and looking in the octoprint.log there is this...

```
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/core.py", line 847, in _import_plugin
    instance = imp.load_module(key, f, filename, description)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_GcodeAnalyzer/__init__.py", line 7, in <module>
    import slic3r
ImportError: No module named slic3r
```
![image](https://user-images.githubusercontent.com/5249455/41877576-cb50394e-789f-11e8-868d-9b68f33fdd59.png)

**Comment by jneilliii** [comment]
Took a quick look at your code.  I think the issue is because your Slic3r.js file is not bundled.  You need to add the [AssetPlugin](http://docs.octoprint.org/en/master/plugins/mixins.html#assetplugin) mixin to include the additional files so the class is imported properly.  You may want to consider changing the name maybe as well, as their may be conflicts with the Slic3r plugin?

**Comment by jneilliii** [comment]
I take that back...your file is a python file...not sure how to include that as an additional resource.

**Comment by eyal0** [comment]
Thanks for testing! I'll take a look.

**Comment by eyal0** [comment]
I tried it on my computer and it worked fine, even without changing the name.  However, I have changed the name.  Try again?

**Comment by jneilliii** [comment]
I just tried again and saw the same thing.  Of course, this time with the new name in the traceback error.  Here's my log. I made sure to delete it prior to attempting the install to insure that it was clean.

[octoprint (3).log](https://github.com/eyal0/OctoPrint-GcodeAnalyzer/files/2137632/octoprint.3.log)

**Comment by eyal0** [comment]
Bizarre.  Can you check if this file exists on your RPi:

`/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_GcodeAnalyzer/analyze_slic3r.py`

?

**Comment by eyal0** [comment]
If that file exists, perhaps try changing the line that says:

`import analyze_slic3r`

to 

`import .analyze_slic3r`

**Comment by eyal0** [comment]
http://www.daveoncode.com/2017/03/07/how-to-solve-python-modulenotfound-no-module-named-import-error/

Maybe

`from . import analyze_slic3r`

**Comment by jneilliii** [comment]
sorry, no love there either.  Error changes...
```
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/core.py", line 847, in _import_plugin
    instance = imp.load_module(key, f, filename, description)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_GcodeAnalyzer/__init__.py", line 7
    import . analyze_slic3r
           ^
SyntaxError: invalid syntax
```

I tried a couple of different pathing options, all with the same error.

``
import .analyze_slic3r
```
and
```
import ./analyze_slic3r
```

Same result.  Maybe there a missing dependency in that py file, which doesn't allow it to compile properly?  Wish I was more help, don't really know python very well.

**Comment by eyal0** [comment]
You tried `from . import analyze_slic3r`?

And did you check that the file analyze_slic3r.py actually exists there?

**Comment by jneilliii** [comment]
Sorry about that, missed that post while I was typing the other one probably.  That seemed to have done the trick,  Plugin is now showing in Software Update & Plugin Manager. I'll do some testing tonight when I get home after work on the analysis side and report back.

**Comment by jneilliii** [comment]
Just did my first gcode upload...works great.  Nearly instant results.

```
2018-06-26 23:44:47,428 - octoprint.filemanager.analysis - INFO - Starting analysis of local:SpiceRackSmallerTest_PET_1.75.gcode
2018-06-26 23:44:47,429 - octoprint.filemanager.analysis - INFO - GcodeAnalyzer starting on /home/pi/.octoprint/uploads/SpiceRackSmallerTest_PET_1.75.gcode
2018-06-26 23:44:47,684 - octoprint.filemanager.analysis - INFO - GcodeAnalyzer results {u'estimatedPrintTime': 3572.0, u'filament': {u'tool0': {u'volume': 8.1, u'length': 3356.1}}}
2018-06-26 23:44:47,685 - octoprint.filemanager.analysis - INFO - Analysis of entry local:SpiceRackSmallerTest_PET_1.75.gcode finished, needed 0.26s
```

**Comment by eyal0** [comment]
Glad to hear!

Maybe @bdynamic @@marcboivin will do testing too?

**Comment by bdynamic** [comment]
@eyal0 Thanks for the plugin. I had to install a new test octopi hence I could just now start testing.
The tests I performed:
- test a gcode with original slic3r time information in it
- test a gcode with modified slic3r time information in it (set it to big number)
- test a gcode with erased time information.

All three tests went through well. The time out of the slic3r file get immediately correctly displayed as "estimated printtime" (in the upper section - screenshot). In case of a file without time information internal estimation takes over. After starting printing the lower time (estimated remaining time) is done by octoprint internally (I guess this is unpreventable?). Of course this time stabilizes over time but some rather huge jumps there. (as said before I guess this is not preventable)

Thanks a lot for the plugin again. The only "feature" I could think of is to display an ETA based on the time from the file...

![auswahl_005](https://user-images.githubusercontent.com/12560294/41989051-504e2724-7a3e-11e8-8e69-6ec4fc1322b9.png)

Additionally I did the following misuse/robustness tests:
- Adding a space between before the "minutes" --> Minutes seem to get ignored
- Setting time line to ; estimated printing time = 4m 80000s  --> time is correctly calculated
- The following line results in a 12 day estimation: ; estimated printing time = 4m 80000d
- Time line with no time given: (; estimated printing time = ) --> no time estimation
- Time line with trash info (; estimated printing time = #!;&%) --> no time estimation

--> I could not get it to crash which is great. Please find also my filtered logfile attached.
[octoprint_filtered.log](https://github.com/eyal0/OctoPrint-GcodeAnalyzer/files/2142253/octoprint_filtered.log)

**Comment by eyal0** [comment]
Cool, thanks!

> Of course this time stabilizes over time but some rather huge jumps there. (as said before I guess this is not preventable)

Actually, maybe it is.  I have a cool idea about how to solve this problem:

Right now, OctoPrint estimates progress using the percentage of the file that is done.  So if X% of the file has been processed, it assumes that X% of the printing is done.  And it knows now long printing has been going so far so it calculates the final time based on that.  This is not an accurate method because one line of gcode can be a tiny move or be a really long move.

I want to write a plugin that will analyze files and determine the time to print each line.  Then I'll store that in metadata about the file so that when progress is reported, it can use the results of the analysis instead of just percentage of bytes.

I'm going to do some testing to see if it can work.

---

> Adding a space between before the "minutes" --> Minutes seem to get ignored

I'll repair that.

> The following line results in a 12 day estimation: ; estimated printing time = 4m 80000d

Maybe it was an overflow of a counter?  I don't think that it's a bug in my code so I won't get into it until we see someone actually suffer this problem!

**Comment by eyal0** [comment]
Looking in your logs (thanks for those!) I see that the `estimatedPrintTime` reported for 80000 days is accurate.  So I guess that it's OctoPrint that is failing to show such a large number.  I'm not going to work on that.
